spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        serviceName: service-producer
        instance-id: ${spring.application.name}:${server.port}
  application:
    name: cloud-consul-producer
server:
  port: 8501
