server:
  port: 8102
spring:
  application:
    name: bus-config-client
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh

  endpoint:
    bus-env:
      enabled: true
    bus-refresh:
      enabled: true
