server:
  port: 8080
spring:
  cloud:
    ##指定注册中心
    consul:
      host: localhost
      port: 8500
      #下面的可选,如果有则在consul管理页面可以显示该服务
      discovery:
        register: true
        service-name: sleuth-gateway-service
        instance-id: ${spring.application.name}:${server.port}
    gateway:
      discovery:
        locator:
          enabled: true #打开与注册中心交互并使用注册中心中相应的服务API
      routes:
        - id: hello-service
          uri: lb://sleuth-consul-producer #指定远程服务，动态均衡
          predicates:
            - Path=/hello
  application:
    name: sleuth-gateway-service
  zipkin:
    base-url: http://localhost:8900
  sleuth:
    sampler:
      probability: 1.0
logging:
  level:
    org.springframework.cloud.gateway: debug

