server:
  port: 8103
spring:
  application:
    name: bus-config-client
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: refresh